apiVersion: app/v1
kind: Deployment
metadata:
  labels:
    app: nginx-girus
  name: nginx-girus
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-girus
  strategy:
    type: Recreate
  template:
    metadata:
    labels:
      app: nginx
    specs:
      containers:
      - image: nginx:1.16.0
        name: nginx
        resources:
          limites:
            memory: "128Mi"
            cpu: "0.3"
          requests:
            memory: "64Mi"
            cpu: "0.1"